SELECT 'public' as table_schema, 'c3p0_test_table' as table_name, COUNT(*) AS row_count FROM public.c3p0_test_table
UNION ALL SELECT 'public' as table_schema, 't_dummy_city_populator' as table_name, COUNT(*) AS row_count FROM public.t_dummy_city_populator
UNION ALL SELECT 'public' as table_schema, 't_dummy_city_populator_2' as table_name, COUNT(*) AS row_count FROM public.t_dummy_city_populator_2
UNION ALL SELECT 'public' as table_schema, 't_dummy_city_populator_3' as table_name, COUNT(*) AS row_count FROM public.t_dummy_city_populator_3
UNION ALL SELECT 'public' as table_schema, 't_dummy_city_populator_4' as table_name, COUNT(*) AS row_count FROM public.t_dummy_city_populator_4
UNION ALL SELECT 'public' as table_schema, 't_dummy_city_populator_5' as table_name, COUNT(*) AS row_count FROM public.t_dummy_city_populator_5
UNION ALL SELECT 'public' as table_schema, 'temp_alternate_location_data' as table_name, COUNT(*) AS row_count FROM public.temp_alternate_location_data
UNION ALL SELECT 'public' as table_schema, 'temp_counter_location_data' as table_name, COUNT(*) AS row_count FROM public.temp_counter_location_data
UNION ALL SELECT 'public' as table_schema, 'temp_country' as table_name, COUNT(*) AS row_count FROM public.temp_country
UNION ALL SELECT 'public' as table_schema, 'temp_extended_location_data' as table_name, COUNT(*) AS row_count FROM public.temp_extended_location_data
UNION ALL SELECT 'public' as table_schema, 'temp_location_code_extended_data' as table_name, COUNT(*) AS row_count FROM public.temp_location_code_extended_data
UNION ALL SELECT 'public' as table_schema, 'temp_main_org_data' as table_name, COUNT(*) AS row_count FROM public.temp_main_org_data
UNION ALL SELECT 'public' as table_schema, 'temp_org_data' as table_name, COUNT(*) AS row_count FROM public.temp_org_data
UNION ALL SELECT 'public' as table_schema, 'tmp_rate_item' as table_name, COUNT(*) AS row_count FROM public.tmp_rate_item
UNION ALL SELECT 'public' as table_schema, 'tmp_res_rate_item' as table_name, COUNT(*) AS row_count FROM public.tmp_res_rate_item
UNION ALL SELECT 'public' as table_schema, 't_populator_device' as table_name, COUNT(*) AS row_count FROM public.t_populator_device
UNION ALL SELECT 'public' as table_schema, 't_populator_landing_signups' as table_name, COUNT(*) AS row_count FROM public.t_populator_landing_signups
UNION ALL SELECT 'public' as table_schema, 't_populator_person_asset' as table_name, COUNT(*) AS row_count FROM public.t_populator_person_asset
UNION ALL SELECT 'public' as table_schema, 't_populator_unscribed' as table_name, COUNT(*) AS row_count FROM public.t_populator_unscribed
UNION ALL SELECT 'public' as table_schema, 't_stockimg_ail_colors_populator' as table_name, COUNT(*) AS row_count FROM public.t_stockimg_ail_colors_populator
UNION ALL SELECT 'public' as table_schema, 't_stockimg_dir' as table_name, COUNT(*) AS row_count FROM public.t_stockimg_dir
UNION ALL SELECT 'public' as table_schema, 't_stockimg_viflist_populator' as table_name, COUNT(*) AS row_count FROM public.t_stockimg_viflist_populator
UNION ALL SELECT 'public' as table_schema, 't_temp_populate_employee' as table_name, COUNT(*) AS row_count FROM public.t_temp_populate_employee
UNION ALL SELECT 'public' as table_schema, 't_tsd_cfleet_to_ti_matching' as table_name, COUNT(*) AS row_count FROM public.t_tsd_cfleet_to_ti_matching
UNION ALL SELECT 'public' as table_schema, 't_tsd_cnotes_to_ti_matching' as table_name, COUNT(*) AS row_count FROM public.t_tsd_cnotes_to_ti_matching
UNION ALL SELECT 'public' as table_schema, 't_tsd_cra001_to_ti_matching' as table_name, COUNT(*) AS row_count FROM public.t_tsd_cra001_to_ti_matching
UNION ALL SELECT 'public' as table_schema, 't_tsd_cradriver_to_ti_matching' as table_name, COUNT(*) AS row_count FROM public.t_tsd_cradriver_to_ti_matching
UNION ALL SELECT 'public' as table_schema, 'v_role_id_sunset' as table_name, COUNT(*) AS row_count FROM public.v_role_id_sunset
UNION ALL SELECT 'public' as table_schema, 'v_total_amount' as table_name, COUNT(*) AS row_count FROM public.v_total_amount
UNION ALL SELECT 'tsd' as table_schema, 't_activity_log_integ_knum' as table_name, COUNT(*) AS row_count FROM tsd.t_activity_log_integ_knum
UNION ALL SELECT 'tsd' as table_schema, 't_adp_email_exceptions' as table_name, COUNT(*) AS row_count FROM tsd.t_adp_email_exceptions
UNION ALL SELECT 'tsd' as table_schema, 't_adp_email_exceptions_2nd_pass' as table_name, COUNT(*) AS row_count FROM tsd.t_adp_email_exceptions_2nd_pass
UNION ALL SELECT 'tsd' as table_schema, 't_date_dimension' as table_name, COUNT(*) AS row_count FROM tsd.t_date_dimension
UNION ALL SELECT 'tsd' as table_schema, 't_deadbeat_matched' as table_name, COUNT(*) AS row_count FROM tsd.t_deadbeat_matched
UNION ALL SELECT 'tsd' as table_schema, 'temp_adp_ti_update_process_active' as table_name, COUNT(*) AS row_count FROM tsd.temp_adp_ti_update_process_active
UNION ALL SELECT 'tsd' as table_schema, 'temp_adp_ti_update_process_inactive' as table_name, COUNT(*) AS row_count FROM tsd.temp_adp_ti_update_process_inactive
UNION ALL SELECT 'tsd' as table_schema, 'temp_deadbeat_active' as table_name, COUNT(*) AS row_count FROM tsd.temp_deadbeat_active
UNION ALL SELECT 'tsd' as table_schema, 'temp_deadbeat_suspended' as table_name, COUNT(*) AS row_count FROM tsd.temp_deadbeat_suspended
UNION ALL SELECT 'tsd' as table_schema, 'temp_tsd_primary' as table_name, COUNT(*) AS row_count FROM tsd.temp_tsd_primary
UNION ALL SELECT 'tsd' as table_schema, 'temp_tsd_primary_address' as table_name, COUNT(*) AS row_count FROM tsd.temp_tsd_primary_address
UNION ALL SELECT 'tsd' as table_schema, 't_fox_csod_users' as table_name, COUNT(*) AS row_count FROM tsd.t_fox_csod_users
UNION ALL SELECT 'tsd' as table_schema, 't_fox_tsd_loctaxes_hourly' as table_name, COUNT(*) AS row_count FROM tsd.t_fox_tsd_loctaxes_hourly
UNION ALL SELECT 'tsd' as table_schema, 't_fox_tsd_reservation_web_loyalty' as table_name, COUNT(*) AS row_count FROM tsd.t_fox_tsd_reservation_web_loyalty
UNION ALL SELECT 'tsd' as table_schema, 't_fox_tsd_to_xp_cancelled_reservations' as table_name, COUNT(*) AS row_count FROM tsd.t_fox_tsd_to_xp_cancelled_reservations
UNION ALL SELECT 'tsd' as table_schema, 't_license_with_expiration_date_matched' as table_name, COUNT(*) AS row_count FROM tsd.t_license_with_expiration_date_matched
UNION ALL SELECT 'tsd' as table_schema, 't_org_unit_adp_location_id' as table_name, COUNT(*) AS row_count FROM tsd.t_org_unit_adp_location_id
UNION ALL SELECT 'tsd' as table_schema, 't_primarydrivers' as table_name, COUNT(*) AS row_count FROM tsd.t_primarydrivers
UNION ALL SELECT 'tsd' as table_schema, 't_reservation_for_update' as table_name, COUNT(*) AS row_count FROM tsd.t_reservation_for_update
UNION ALL SELECT 'tsd' as table_schema, 't_reservation_for_update_not_converted' as table_name, COUNT(*) AS row_count FROM tsd.t_reservation_for_update_not_converted
UNION ALL SELECT 'tsd' as table_schema, 't_secondarydrivers' as table_name, COUNT(*) AS row_count FROM tsd.t_secondarydrivers
UNION ALL SELECT 'tsd' as table_schema, 't_service_agent_associate' as table_name, COUNT(*) AS row_count FROM tsd.t_service_agent_associate
UNION ALL SELECT 'tsd' as table_schema, 't_tsd_to_ti_unique_license_for_webloyalty' as table_name, COUNT(*) AS row_count FROM tsd.t_tsd_to_ti_unique_license_for_webloyalty
UNION ALL SELECT 'tsd' as table_schema, 't_webloyalty_rez_jsi_matched' as table_name, COUNT(*) AS row_count FROM tsd.t_webloyalty_rez_jsi_matched
